sudo: false
cache:
  bundler: true
  directories:
  - cache/
notification:
  email: false
language: c
compiler: gcc

branches:
  only:
    - master

env:
  global:
    - PACKAGE=tunet
  matrix:
    - SDK_URL=https://downloads.openwrt.org/chaos_calmer/15.05/ar71xx/generic/OpenWrt-SDK-15.05-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2
    - SDK_URL=https://downloads.openwrt.org/chaos_calmer/15.05/kirkwood/generic/OpenWrt-SDK-15.05-kirkwood_gcc-4.8-linaro_uClibc-0.9.33.2_eabi.Linux-x86_64.tar.bz2
    - SDK_URL=https://downloads.openwrt.org/chaos_calmer/15.05/lantiq/xway/OpenWrt-SDK-15.05-lantiq-xway_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2
    - SDK_URL=https://downloads.openwrt.org/chaos_calmer/15.05/ramips/rt305x/OpenWrt-SDK-15.05-ramips-rt305x_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2

install:
  - mkdir -p $TRAVIS_BUILD_DIR/local ; cd $TRAVIS_BUILD_DIR/local
  - wget "http://us.archive.ubuntu.com/ubuntu/pool/main/c/ccache/ccache_3.1.6-1_amd64.deb"
  - dpkg -x *.deb .
  - mkdir -p $TRAVIS_BUILD_DIR/cache ; cd $TRAVIS_BUILD_DIR/cache
  - wget -c $SDK_URL
  - mkdir -p $TRAVIS_BUILD_DIR/sdk ; cd $TRAVIS_BUILD_DIR/sdk
  - export FILE=$TRAVIS_BUILD_DIR/cache/$(basename $SDK_URL)
  - file $FILE
  - tar xjf $FILE
  - cd $TRAVIS_BUILD_DIR/sdk/OpenWrt-SDK-*
  - export SDK_DIR=$PWD
#  - mkdir package/$PACKAGE
#  - ln -s $TRAVIS_BUILD_DIR/Tunet/Makefile package/$PACKAGE/
#  - ln -s $TRAVIS_BUILD_DIR/Tunet package/$PACKAGE/src

script:
  - cd $TRAVIS_BUILD_DIR
  - ./rebuild-cross-compile.sh $SDK_DIR
  - file src/tunet
#  - export PATH=$TRAVIS_BUILD_DIR/local/usr/bin:$PATH
#  - cd $TRAVIS_BUILD_DIR/sdk/OpenWrt-SDK-*
#  - ./scripts/feeds update packages >/dev/null
#  - ./scripts/feeds install libpthread

